//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValutaConsole.ValutaWcfService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValutaWcfService.IValutaService")]
    public interface IValutaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/FromDkkToEur", ReplyAction="http://tempuri.org/IValutaService/FromDkkToEurResponse")]
        decimal FromDkkToEur(decimal dkkAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/FromDkkToEur", ReplyAction="http://tempuri.org/IValutaService/FromDkkToEurResponse")]
        System.Threading.Tasks.Task<decimal> FromDkkToEurAsync(decimal dkkAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetExchangeRate", ReplyAction="http://tempuri.org/IValutaService/GetExchangeRateResponse")]
        decimal GetExchangeRate(string iso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetExchangeRate", ReplyAction="http://tempuri.org/IValutaService/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<decimal> GetExchangeRateAsync(string iso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValutaServiceChannel : ValutaConsole.ValutaWcfService.IValutaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValutaServiceClient : System.ServiceModel.ClientBase<ValutaConsole.ValutaWcfService.IValutaService>, ValutaConsole.ValutaWcfService.IValutaService {
        
        public ValutaServiceClient() {
        }
        
        public ValutaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValutaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValutaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValutaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal FromDkkToEur(decimal dkkAmount) {
            return base.Channel.FromDkkToEur(dkkAmount);
        }
        
        public System.Threading.Tasks.Task<decimal> FromDkkToEurAsync(decimal dkkAmount) {
            return base.Channel.FromDkkToEurAsync(dkkAmount);
        }
        
        public decimal GetExchangeRate(string iso) {
            return base.Channel.GetExchangeRate(iso);
        }
        
        public System.Threading.Tasks.Task<decimal> GetExchangeRateAsync(string iso) {
            return base.Channel.GetExchangeRateAsync(iso);
        }
    }
}
