//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValutaConsole.ValutaWcfService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Valuta", Namespace="http://schemas.datacontract.org/2004/07/ValutaWcfService")]
    [System.SerializableAttribute()]
    public partial class Valuta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExchangeRate {
            get {
                return this.ExchangeRateField;
            }
            set {
                if ((this.ExchangeRateField.Equals(value) != true)) {
                    this.ExchangeRateField = value;
                    this.RaisePropertyChanged("ExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Iso {
            get {
                return this.IsoField;
            }
            set {
                if ((object.ReferenceEquals(this.IsoField, value) != true)) {
                    this.IsoField = value;
                    this.RaisePropertyChanged("Iso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValutaWcfService.IValutaService")]
    public interface IValutaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/FromDkkToEur", ReplyAction="http://tempuri.org/IValutaService/FromDkkToEurResponse")]
        decimal FromDkkToEur(decimal dkkAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/FromDkkToEur", ReplyAction="http://tempuri.org/IValutaService/FromDkkToEurResponse")]
        System.Threading.Tasks.Task<decimal> FromDkkToEurAsync(decimal dkkAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetExchangeRate", ReplyAction="http://tempuri.org/IValutaService/GetExchangeRateResponse")]
        decimal GetExchangeRate(string iso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetExchangeRate", ReplyAction="http://tempuri.org/IValutaService/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<decimal> GetExchangeRateAsync(string iso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetValutas", ReplyAction="http://tempuri.org/IValutaService/GetValutasResponse")]
        ValutaConsole.ValutaWcfService.Valuta[] GetValutas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetValutas", ReplyAction="http://tempuri.org/IValutaService/GetValutasResponse")]
        System.Threading.Tasks.Task<ValutaConsole.ValutaWcfService.Valuta[]> GetValutasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/ConvertFromIsoToIso", ReplyAction="http://tempuri.org/IValutaService/ConvertFromIsoToIsoResponse")]
        decimal ConvertFromIsoToIso(string fromIso, string toIso, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/ConvertFromIsoToIso", ReplyAction="http://tempuri.org/IValutaService/ConvertFromIsoToIsoResponse")]
        System.Threading.Tasks.Task<decimal> ConvertFromIsoToIsoAsync(string fromIso, string toIso, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetDoneConversions", ReplyAction="http://tempuri.org/IValutaService/GetDoneConversionsResponse")]
        string[] GetDoneConversions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaService/GetDoneConversions", ReplyAction="http://tempuri.org/IValutaService/GetDoneConversionsResponse")]
        System.Threading.Tasks.Task<string[]> GetDoneConversionsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValutaServiceChannel : ValutaConsole.ValutaWcfService.IValutaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValutaServiceClient : System.ServiceModel.ClientBase<ValutaConsole.ValutaWcfService.IValutaService>, ValutaConsole.ValutaWcfService.IValutaService {
        
        public ValutaServiceClient() {
        }
        
        public ValutaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValutaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValutaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValutaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal FromDkkToEur(decimal dkkAmount) {
            return base.Channel.FromDkkToEur(dkkAmount);
        }
        
        public System.Threading.Tasks.Task<decimal> FromDkkToEurAsync(decimal dkkAmount) {
            return base.Channel.FromDkkToEurAsync(dkkAmount);
        }
        
        public decimal GetExchangeRate(string iso) {
            return base.Channel.GetExchangeRate(iso);
        }
        
        public System.Threading.Tasks.Task<decimal> GetExchangeRateAsync(string iso) {
            return base.Channel.GetExchangeRateAsync(iso);
        }
        
        public ValutaConsole.ValutaWcfService.Valuta[] GetValutas() {
            return base.Channel.GetValutas();
        }
        
        public System.Threading.Tasks.Task<ValutaConsole.ValutaWcfService.Valuta[]> GetValutasAsync() {
            return base.Channel.GetValutasAsync();
        }
        
        public decimal ConvertFromIsoToIso(string fromIso, string toIso, decimal amount) {
            return base.Channel.ConvertFromIsoToIso(fromIso, toIso, amount);
        }
        
        public System.Threading.Tasks.Task<decimal> ConvertFromIsoToIsoAsync(string fromIso, string toIso, decimal amount) {
            return base.Channel.ConvertFromIsoToIsoAsync(fromIso, toIso, amount);
        }
        
        public string[] GetDoneConversions() {
            return base.Channel.GetDoneConversions();
        }
        
        public System.Threading.Tasks.Task<string[]> GetDoneConversionsAsync() {
            return base.Channel.GetDoneConversionsAsync();
        }
    }
}
